openapi: '3.0.0'
info:
    title: API docs
    description: Example swagger docs.
    version: 1.0.0

servers:
#    -   url: https://google.com
#    -   url: /app/health
    -   url: /example
        description: Google example

paths:
    # ======================== Example ========================
    /:
        post:
            summary: Get request example.
            tags:
                - Google
            responses:
                200:
                    description: OK
